export const WEATHER_INFO_SETTING = 'USER_INFO_SETTINGS';
export const CITY_INFO_SETTING = 'CITY_INFO_SETTING';
export const DATE_INFO_SETTING = 'DATE_INFO_SETTING';
export const ATMOSPHERE_INFO_SETTING = 'ATMOSPHERE_INFO_SETTING';
export const LOADING_STATE_SETTING = 'LOADING_STATE_SETTING';
